////////////////////////////////////////////////////////////////////////////////
//  Copyright 2018 James Fenn
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
////////////////////////////////////////////////////////////////////////////////

#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl1,  encoder3,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoder4,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchSensor4,   sensorTouch)
#pragma config(Sensor, dgtl6,  touchSensor3,   sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           armMotor3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           strongArm,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           strongArm2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           klaw1,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           klaw2,         tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float getSpeed();
int motor3Value;
int strongArmValue;

bool klaw;

task main() {

	SensorValue[encoder3] = 0;
	SensorValue[encoder4] = 0;

	while (true) {

		//drive motors
		motor[rightMotor] = (vexRT[Ch4] - vexRT[Ch3] - vexRT[Ch2] + vexRT[Ch1] + motor[rightMotor]) / 3;
		motor[leftMotor] = (-vexRT[Ch4] - vexRT[Ch3] - vexRT[Ch2] - vexRT[Ch1] + motor[rightMotor]) / 3;

		//upper arm motor
		if (vexRT[Btn5U] && !SensorValue(touchSensor3)) {
			motor[armMotor3] = -getSpeed();
			motor3Value = SensorValue(encoder3);
		} else if (vexRT[Btn5D] && SensorValue(encoder3) > -200) {
			motor[armMotor3] = getSpeed();
			motor3Value = SensorValue(encoder3);
		} else if (vexRT[Btn7U]) {
			motor[armMotor3] = SensorValue(encoder3) + 150;
			motor3Value = SensorValue(encoder3);
		} else {
			motor[armMotor3] = SensorValue(encoder3) - motor3Value;
		}
		
		if (SensorValue(touchSensor3)) {
			motor3Value = 0;
			SensorValue[encoder3] = 0;
		}

		//lower arm motors
		if (vexRT[Btn6U] && SensorValue(encoder4) < 450) {
			motor[strongArm] = -getSpeed();
			motor[strongArm2] = -getSpeed();
			strongArmValue = 3.5 * SensorValue(encoder4);
		} else if (vexRT[Btn6D] && !SensorValue(touchSensor4)) {
			motor[strongArm] = getSpeed();
			motor[strongArm2] = getSpeed();
			strongArmValue = 3.5 * SensorValue(encoder4);
		} else if (vexRT[Btn7U]) {
			motor[strongArm] = (3.5 * SensorValue(encoder4)) - 360;
			motor[strongArm2] = (3.5 * SensorValue(encoder4)) - 360;
			strongArmValue = 3.5 * SensorValue(encoder4);
		} else {
			motor[strongArm] = (3.5 * SensorValue(encoder4)) - strongArmValue;
			motor[strongArm2] = (3.5 * SensorValue(encoder4)) - strongArmValue;
		}
		
		if (SensorValue(touchSensor4)) {
			strongArmValue = 0;
			SensorValue[encoder4] = 0;
		}

		//set claw open/closed
		if (vexRT[Btn7R]) {
			motor[klaw1] = getSpeed();
			motor[klaw2] = getSpeed();
			klaw = true;
		} else if (vexRT[Btn7L]) {
			motor[klaw1] = -getSpeed();
			motor[klaw2] = -getSpeed();
			klaw = false;
		} else {
			if (klaw) {
        //hold the claw closed
				motor[klaw1] = getSpeed();
				motor[klaw2] = getSpeed();
			} else {
				motor[klaw1] = -5;
				motor[klaw2] = -5;
			}
		}

		//display encoder values on LCD (debug only)
		displayLCDNumber(0, 0, SensorValue(encoder3));
		displayLCDNumber(0, 6, SensorValue(encoder4) * 3.5);

		if (vexRT[Btn7D]) {
			while ((!SensorValue(touchSensor3) || !SensorValue(touchSensor4)) && vexRT[Btn7D]) {
				if (!SensorValue(touchSensor3)) {
					motor[armMotor3] = -70;
					motor3Value = SensorValue(encoder3);
				} else motor[armMotor3] = 0;

				if (!SensorValue(touchSensor4)) {
					motor[strongArm] = 70;
					motor[strongArm2] = 70;
					strongArmValue = 3.5 * SensorValue(encoder4);
				} else {
					motor[strongArm] = 0;
					motor[strongArm2] = 0;
				}
			}

			SensorValue[encoder3] = 0;
			SensorValue[encoder4] = 0;
			motor3Value = 0;
			strongArmValue = 0;
		}
	}
}

float getSpeed() {
	if (vexRT[Btn8R]) return 50;
	else return 127;
}
