////////////////////////////////////////////////////////////////////////////////
//  Copyright 2018 James Fenn
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
////////////////////////////////////////////////////////////////////////////////

#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  touchSensorArm, sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftIntake,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rightIntake,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int speed = 127;
const int turn = 100;

task main() { 
	while(SensorValue(touchSensorArm) == 0) {
		motor[armMotor] = -127;
	}
	motor[armMotor] = 0;

	while(true) {
		if (SensorValue(touchSensorArm) == 0) motor[armMotor] = -1 * speed;
		else motor[armMotor] = 0;

		if (SensorValue(sonarSensor) < 50 && SensorValue(sonarSensor) > 10) {
			motor[armMotor] = speed;
			motor[leftIntake] = -1 * speed;
			motor[rightIntake] = -1 * speed;
			} else if (SensorValue(sonarSensor) < 50) {
			motor[leftMotor] = -1 * turn;
			motor[rightMotor] = turn;
			} else {
			motor[leftMotor] = speed;
			motor[rightMotor] = speed;
		}
	}
}


