#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  touchSensorArm, sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftIntake,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rightIntake,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int speed = 127;
const int turn = 100;

task main() { 
	while(SensorValue(touchSensorArm) == 0) {
		motor[armMotor] = -127;
	}
	motor[armMotor] = 0;

	while(true) {
		if (SensorValue(touchSensorArm) == 0) motor[armMotor] = -1 * speed;
		else motor[armMotor] = 0;

		if (SensorValue(sonarSensor) < 50 && SensorValue(sonarSensor) > 10) {
			motor[armMotor] = speed;
			motor[leftIntake] = -1 * speed;
			motor[rightIntake] = -1 * speed;
			} else if (SensorValue(sonarSensor) < 50) {
			motor[leftMotor] = -1 * turn;
			motor[rightMotor] = turn;
			} else {
			motor[leftMotor] = speed;
			motor[rightMotor] = speed;
		}
	}
}


