#pragma config(Sensor, dgtl3,  touchSensorArm, sensorTouch)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftIntake,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rightIntake,   tmotorServoStandard, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int r;
int l;
int a;

task main()
{  	
    while (true) {
  	 if (vexRT[Btn5U] == 1) {
  		r = vexRT[Ch2] + (-1 * (vexRT[Ch1] / 2));
	    l = vexRT[Ch2] + (vexRT[Ch1] / 2);
        
		if (r > 127) r = 127;
		else if (r < -127) r = -127;
		if (l > 127) l = 127;
		else if (l < -127) l = -127;
  	 } else {
  		r = (vexRT[Ch2] + (-1 * vexRT[Ch1])) / 3;
		l = (vexRT[Ch2] + vexRT[Ch1]) / 3;
  	 }
  	
  	 motor[rightMotor] = r;
     motor[leftMotor] = l;
     
     a = vexRT[Ch3];
     if (a < 0 && SensorValue(touchSensorArm) == 0) {
       motor[armMotor] = a;
     } else if (a > 0) {
      motor[armMotor] = a;
   	}
     
     if (vexRT[Btn6U]) {
       motor[leftIntake] = 127;
       motor[rightIntake] = 127;
     } else if (vexRT[Btn6D]) {
       motor[leftIntake] = -127;
       motor[rightIntake] = -127;
     } else {
       motor[leftIntake] = 0;
       motor[rightIntake] = 0;
     }
	}
}


