////////////////////////////////////////////////////////////////////////////////
//  Copyright 2018 James Fenn
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
////////////////////////////////////////////////////////////////////////////////

#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightIntake,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           leftIntake,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           thrower,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)

 //*!!Code automatically generated by 'ROBOTC' configuration wizard !!*// 
 
//This program is deprecated because, well, the ultrasonic sensors weren't working properly.
//Keeping this program so I can scream at my horrible code later and possibly use it for something (but probably not).

bool isIntake;
bool intakeHold;

bool isThrower;
bool throwerHold;

task main() { 
while(true) { 
	switch(whatDo()) {
		case 0:
			//intake
			break;
		case 1:
			//move
			break;
		case 2:
			//throw
			break;
	}
}
 }

int whatDo() {
	//evaluate surroundings, return an action
}

void toggleIntake() {
	if (isIntake) {
		//turn motor off
		motor[rightIntake] = 0;
		motor[leftIntake] = 0;
		isIntake = false;
	} else {
		//turn motor on
		motor[rightIntake] = 100;
		motor[leftIntake] = 100;
		isIntake = true;
	}
}

void toggleThrower() {
	if (isThrower) {
		//turn motor off
		motor[thrower] = 0;
		isThrower = false;
	} else {
		//turn motor on
		motor[thrower] = 127;
		isThrower = true;
	}
}

